### ISSUE TITLE
RestClientErrorException: invalid syntax

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#316]
I'm running the latest version and haven't run the code for a few days but I'm now getting the following exception for all of my accounts and I have no clue why or what is causing it. Now due to the new changes I'm guessing, the program doesn't try to reconnect or anything. It just sits there doing nothing after getting this error. Here is the full printout that I get

```
We are waiting for the market to open...
Market opened.
Alpaca streaming client socket opened.
Alpaca streaming client connection status is Authorized.
Alpaca data streaming client socket opened.
Alpaca data streaming client connection status is Authorized.
Alpaca data streaming client error:
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
invalid syntax

Alpaca data streaming client socket opened.
Alpaca data streaming client connection status is Unauthorized.
```

**Comment by ooples** [comment]
Are you still working on a fix for this issue or is it addressed in this latest version?

**Comment by OlegRa** [comment]
@ooples No, it's not fixed and I still have no ideas about the possible root cause of this problem.

**Comment by ooples** [comment]
@OlegRa Can you go ahead and publish a new version with the latest commits? I'm getting errors trying to build the project on my end

**Comment by OlegRa** [comment]
@ooples Unfortunately, I'm still not able to reproduce this problem on my side. All my tests with normal connection or re-connection to this streaming API works fine with the latest available NuGet package. Maybe you do something that works before just by accident? I don't know exactly what can be the root cause of this problem on your side. If you can prepare the simplest possible code example that fails (at least on your side) it would be very helpful.

**Comment by ooples** [comment]
@OlegRa I think the issue is related to the subscriptions because with the latest version installed I'm now not receiving any price updates at all and I have my subscription code below. It was working just fine 2 versions ago btw and I haven't changed anything with it

       `public async Task RunSubscribeProcess()
        {
            try
            {
                var subscription = alpacaDataStreamingClient.GetMinuteAggSubscription();
                var waitObject = new AutoResetEvent(false);
                var cancellationTokenSource = new CancellationTokenSource();
                alpacaDataStreamingClient.Subscribe(subscription);

                Task.Run(async () =>
                {
                    await foreach (var item in subscription
                        .AsAsyncEnumerable(cancellationTokenSource.Token)
                        .ConfigureAwait(false))
                    {
                        AddStockData(item);
                        waitObject.Set();
                    }
                }, cancellationTokenSource.Token);
            }
            catch (Exception ex)
            {
                await Program.ThrowExceptionInfo(ex).ConfigureAwait(false);
            }
        }`

**Comment by OlegRa** [comment]
@ooples Only all symbols subscription doesn't work. I'll check why soon.

**Comment by OlegRa** [comment]
@ooples Just rename `GetMinuteAggSubscription` into `GetMinuteBarSubscription` and it should start working. I'll update names in the extensions package soon.

**Comment by ooples** [comment]
@OlegRa I did the rename but I'm still not getting any updates. I know it is after hours for the stock market so I will usually get much fewer price updates but I'm getting nothing at all

**Comment by ooples** [comment]
@OlegRa I can confirm that with the latest version the variable subscribed is only true during normal market hours but is false during pre market or after market hours. If I go back two versions ago it subscribes to price updates for both normal market hours as well as pre market and after market hours

**Comment by OlegRa** [comment]
@ooples So right now you can build 2 versions:

1. With the old SDK version (I guess 5.0.2-alpha4) that connects and receive data successfully in pre and after-market hours
2. With the one SDK version (5.0.3-alpha2) that connects but doesn't receive any data in pre and after-market hours

And both connect to the same environment with the same credentials (key/secret) and you can run both and check data receiving status? I just know that I've not changed anything related to data subscription in the last weeks so it sounds very strange to me.

**Comment by OlegRa** [comment]
@ooples I'm sure I've seen it in the forum and finally I find it: https://forum.alpaca.markets/t/what-happened-to-premarket-aftermarket-bars/5189/7

**Comment by ooples** [comment]
@OlegRa I know it isn't your fault but this is beyond infuriating that they would release v2 without after hours price data!!

**Comment by OlegRa** [comment]
@ooples In fact, initially they deployed it with this feature but something goes wrong and they had to rollback it :(

**Comment by ooples** [comment]
@OlegRa Well I'm running the latest version now during hours and now I'm getting this new exception for most of my accounts:

Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
Too Many Requests

Exception StackTrace:
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.AlpacaApi.RunSellOrderProcess() in D:\Code Projects\OoplesFinanceAdminClient\AlpacaApi.cs:line 1100

Exception Target Site:
MoveNext

Exception Source:
Alpaca.Markets

**Comment by OlegRa** [comment]
@ooples In fact you've received these errors before but the old throttle handles them better. I'll try to fix it in the scope of issue #237 fixes. If you're not experiencing the original problem (the 'invalid syntax' error), please, close this issue.
